name: flutter_application_2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #intl: ^0.17.0
  http: ^0.13.3
  table_calendar: ^3.0.0
  camera: ^0.10.3+2
  printing: ^5.9.2
  permission_handler: ^10.2.0
  time_range_picker: ^2.2.0
  pdf: ^3.6.0
  path_provider: ^2.0.14
  provider: ^6.1.1
  geolocator: ^7.1.0
  open_file: ^3.2.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  image_picker: ^0.8.7+1
  file_picker: ^4.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/font/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages